# mental-health-assistant/docker-compose.yml
version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:16-alpine # Using a lightweight PostgreSQL image
    restart: always
    environment:
      POSTGRES_DB: mental_health_db # Your database name
      POSTGRES_USER: user # Your database user
      POSTGRES_PASSWORD: password # Your database password (CHANGE THIS FOR PRODUCTION!)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432

  # Ollama Service for Local LLMs
  

  # ChromaDB Service (Optional - You can also run Chroma in-process with Python)
  # If you choose to run Chroma as a separate service, uncomment this block
  # chroma:
  #   image: ghcr.io/chroma-core/chroma:latest
  #   restart: always
  #   volumes:
  #     - chroma_data:/app/chroma/chroma # Persist Chroma data
  #   ports:
  #     - "8000:8000" # Default Chroma port (can conflict with FastAPI, adjust if needed)

volumes:
  postgres_data:
  ollama_models:
  # chroma_data: # Uncomment if using Chroma service