"""Add tags column to mood_entries

Revision ID: 346442987339
Revises: 48f6b8ab5158
Create Date: 2025-07-27 11:07:38.232414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '346442987339'
down_revision: Union[str, None] = '48f6b8ab5158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_entries', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood_entries', 'tags')
    # ### end Alembic commands ###
