"""Add profile fields to User model

Revision ID: 823dda067eae
Revises: 629152903cb0
Create Date: 2025-07-28 08:43:25.873855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '823dda067eae'
down_revision: Union[str, None] = '629152903cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('triggers', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('areas_of_focus', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'areas_of_focus')
    op.drop_column('users', 'triggers')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
