"""Add sentiment fields to journal_entries

Revision ID: b8d35e24902c
Revises: 823dda067eae
Create Date: 2025-07-28 11:21:00.331282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d35e24902c'
down_revision: Union[str, None] = '823dda067eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('sentiment_label', sa.String(), nullable=True))
    op.add_column('journal_entries', sa.Column('sentiment_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'sentiment_score')
    op.drop_column('journal_entries', 'sentiment_label')
    # ### end Alembic commands ###
